(define (problem basico1) 
  (:domain planningbooks) 
  (:objects   libro_0  libro_1  libro_2  libro_3  libro_4  libro_5  libro_6  libro_7  libro_8  libro_9  libro_10  libro_11  libro_12  libro_13  libro_14  - libro 
  enero febrero marzo abril mayo junio julio agosto setiembre octubre noviembre diciembre fin fin2 - mes
 )
(:init
  (mes_actual enero)  (mes_siguiente enero febrero)   (mes_siguiente febrero marzo)  (mes_siguiente marzo abril)  (mes_siguiente abril mayo)  (mes_siguiente mayo junio)  (mes_siguiente junio julio)  (mes_siguiente julio agosto)  (mes_siguiente agosto setiembre)  (mes_siguiente setiembre octubre)  (mes_siguiente octubre noviembre)  (mes_siguiente noviembre diciembre)  (mes_siguiente diciembre fin)  (mes_siguiente diciembre fin2) 
   (paralelo libro_0 libro_1)  (paralelo libro_1 libro_0)  (paralelo libro_2 libro_3)  (paralelo libro_3 libro_2)  (paralelo libro_4 libro_5)  (paralelo libro_5 libro_4)  (paralelo libro_6 libro_7)  (paralelo libro_7 libro_6)  (paralelo libro_8 libro_9)  (paralelo libro_9 libro_8)  (paralelo libro_10 libro_11)  (paralelo libro_11 libro_10)  (paralelo libro_12 libro_13)  (paralelo libro_13 libro_12) 
  (predecessor libro_2 libro_0) 
  (predecessor libro_3 libro_0) (predecessor libro_4 libro_0) (predecessor libro_5 libro_0) (predecessor libro_6 libro_0) (predecessor libro_7 libro_0) 
  (predecessor libro_8 libro_0) (predecessor libro_10 libro_0) (predecessor libro_11 libro_0) (predecessor libro_12 libro_0) (predecessor libro_13 libro_0) 
  (predecessor libro_14 libro_0) (predecessor libro_2 libro_1) (predecessor libro_3 libro_1) (predecessor libro_5 libro_1) (predecessor libro_6 libro_1) 
  (predecessor libro_7 libro_1) (predecessor libro_8 libro_1) (predecessor libro_9 libro_1) (predecessor libro_10 libro_1) (predecessor libro_11 libro_1) 
  (predecessor libro_12 libro_1) (predecessor libro_13 libro_1) (predecessor libro_14 libro_1) (predecessor libro_4 libro_2) (predecessor libro_5 libro_2) 
  (predecessor libro_7 libro_2) (predecessor libro_8 libro_2) (predecessor libro_9 libro_2) (predecessor libro_10 libro_2) (predecessor libro_11 libro_2) 
  (predecessor libro_12 libro_2) (predecessor libro_13 libro_2) (predecessor libro_14 libro_2) (predecessor libro_4 libro_3) (predecessor libro_5 libro_3) 
  (predecessor libro_6 libro_3) (predecessor libro_7 libro_3) (predecessor libro_8 libro_3) (predecessor libro_9 libro_3) (predecessor libro_10 libro_3) 
  (predecessor libro_11 libro_3) (predecessor libro_14 libro_3) (predecessor libro_7 libro_4) (predecessor libro_8 libro_4) (predecessor libro_9 libro_4) 
  (predecessor libro_11 libro_4) (predecessor libro_12 libro_4) (predecessor libro_13 libro_4) (predecessor libro_14 libro_4) (predecessor libro_6 libro_5) 
  (predecessor libro_7 libro_5) (predecessor libro_8 libro_5) (predecessor libro_9 libro_5) (predecessor libro_10 libro_5) (predecessor libro_11 libro_5) 
  (predecessor libro_12 libro_5) (predecessor libro_13 libro_5) (predecessor libro_14 libro_5) (predecessor libro_8 libro_6) (predecessor libro_9 libro_6) 
  (predecessor libro_10 libro_6) (predecessor libro_11 libro_6) (predecessor libro_12 libro_6) (predecessor libro_13 libro_6) (predecessor libro_8 libro_7) 
  (predecessor libro_9 libro_7) (predecessor libro_10 libro_7) (predecessor libro_11 libro_7) (predecessor libro_12 libro_7) (predecessor libro_13 libro_7) 
  (predecessor libro_14 libro_7) (predecessor libro_10 libro_8) (predecessor libro_11 libro_8) (predecessor libro_12 libro_8) (predecessor libro_13 libro_8) 
  (predecessor libro_14 libro_8) (predecessor libro_10 libro_9) (predecessor libro_11 libro_9) (predecessor libro_12 libro_9) (predecessor libro_13 libro_9) 
  (predecessor libro_14 libro_9) (predecessor libro_12 libro_10) (predecessor libro_13 libro_10) (predecessor libro_12 libro_11) (predecessor libro_13 libro_11) 
  (predecessor libro_14 libro_11) (predecessor libro_14 libro_12) (predecessor libro_14 libro_13) 
   (deseado libro_3)  (deseado libro_1)  (deseado libro_12)  (deseado libro_13)  (deseado libro_5) 
  (leido libro_10)  (leido libro_2)  (leido libro_0)  (leido libro_9)  (leido libro_4)
 (es_fi fin) (es_fi fin2)
)
(:goal (and 
 forall (?l libro) (imply (deseado ?l) (leido ?l)))
))