(define (domain basic)
  (:requirements :strips :typing)
  (:types libro - object)

  (:predicates (leido ?l - libro)
               (deseado ?l - libro)
               (predecesor ?l - libro ?lp - libro)
  )

  (:action leer
    :parameters (?l - libro)
    :precondition (and (not (leido ?l))
                       (or (deseado ?l) (exists (?p - libro) (and (predecesor ?p ?l)
                                                                  (deseado ?p)))
                       )
                       (not (exists (?p - libro) (and (predecesor ?l ?p) 
                                                      (not (leido ?p))))
                       )
                  )
    :effect (and (leido ?l))
  )
)
